# -*- coding: utf-8 -*-
"""Amazon_Sales_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqhqAkyjCzBlB1BF_Pv0wflMShKzMTJr
"""

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Internships/Unified Mentor/Amazon Sales data.csv")

data.head()

data.duplicated().sum()

data.info()

data.shape

df = data.describe().astype(int)
df

for i in df.columns:
  data[i].astype(int)

df = data.groupby(['Region'])[['Units Sold']].sum()
df

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20,8))
sns.countplot(x=data['Region'],hue=data['Region'])
plt.title('Region wise Sales Count')
plt.show()

plt.figure(figsize=(20,8))
sns.barplot(x=data['Item Type'],y=data['Total Revenue'],hue=data['Item Type'])
plt.title('Total Revenue Generated by Each Item Type')
plt.show()

plt.figure(figsize=(20,8))
sns.scatterplot(x=data['Item Type'],y=data['Units Sold'],hue=data['Sales Channel'])
plt.title('Item Type Sales By Sales Channel')
plt.show()

sns.histplot(x=data['Unit Cost'])

sns.histplot(x=data['Unit Price'],hue=data['Sales Channel'])

plt.figure(figsize=(20,8))
sns.scatterplot(x=data['Units Sold'],y=data['Unit Price'],hue=data['Sales Channel'])

plt.figure(figsize=(20,8))
sns.barplot(y=data['Units Sold'],x=data['Unit Price'],hue=data['Sales Channel'])