# -*- coding: utf-8 -*-
"""UnifiedBudgetSalesData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0TDGLr860jBVIopvC-kRr2yh3zlWYvX
"""

import pandas as pd

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

budget = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/Budget.xlsx - Budget.csv')
budget.head()

calender = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/AdventureWorks_Database.xlsx - Calender.csv')
calender.head()

customer = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/AdventureWorks_Database.xlsx - Customers.csv')
customer.head()

product = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/AdventureWorks_Database.xlsx - Product.csv')
product.head()

sales = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/AdventureWorks_Database.xlsx - Sales.csv')
sales = sales.iloc[:,0:13]
sales.head()

territory = pd.read_csv('/content/drive/MyDrive/Internships/Unified Mentor/Budget Sales data/AdventureWorks_Database.xlsx - Territory.csv')
territory.head()

sales_prod = pd.merge(product,sales,on='ProductKey')
sales_prod.head()

sales_prod_cust = pd.merge(sales_prod,customer,on='CustomerKey')

sales_prod_cust_terr = pd.merge(sales_prod_cust,territory,on='SalesTerritoryKey')

sales_prod_cust_terr.shape

sales_prod_cust_terr.head()

sales_prod_cust_terr.groupby(['Country','ProductName'])[['OrderQuantity']].count()

sales_prod_cust_terr.isnull().sum()

sales_prod_cust_terr.to_csv('merged.csv')
sales_prod_cust_terr.head()

sales_prod_cust_terr.groupby(['Category','ProductName'])[['OrderQuantity']].count()

data = sales_prod_cust_terr

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20,8))
sns.countplot(x=data['Category'],hue=data['Category'])
plt.title('Category wise Sales Count')
plt.show()

plt.figure(figsize=(20,8))
sns.barplot(x=data['SubCategory'],y=data['OrderQuantity'],hue=data['SubCategory'])
plt.title('Total Revenue Generated by Each Item Type')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(20,8))
sns.scatterplot(y=data['SubCategory'],x=data['OrderQuantity'],hue=data['Gender'])
plt.title('Item Type Sales By Sales Channel')
plt.show()

plt.figure(figsize=(20,8))
sns.histplot(x=data['YearlyIncome'])

plt.figure(figsize=(20,8))
sns.barplot(y=data['YearlyIncome'],x=data['Occupation'],hue=data['HouseOwnerFlag'])









